### ISSUE TITLE
Do not clear cookies if they do not exist in the first place

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-javalin#6]
Refer to supertokens/supertokens-node#17

**Comment by jscyo** [comment]
#### There is a race condition:

- Request1 is fired
- Request2 is fired
- Request1 creates a session
- Request2 calls getSession to check if a session exists
- Request1 returns cookies to the frontend
- Request2 clears cookies since the session does not exist
- The user is left with no session

#### To prevent the race condition the following changes need to be made:
- You need to remove the call to ``clearSessionFromCookie()`` in the [getSession](https://github.com/supertokens/supertokens-javalin/blob/master/src/main/java/io/supertokens/javalin/SuperTokens.java#L68) function when the ``idRefreshToken`` from the cookie is ``null``.
 -  You need to remove the call to ``clearSessionFromCookie()`` in the [refreshSession](https://github.com/supertokens/supertokens-javalin/blob/master/src/main/java/io/supertokens/javalin/SuperTokens.java#L111) function when the ``inputRefreshToken`` from the cookie is ``null``.

#### Add the following tests
- test that ``getSession`` does not clear cookies if a session does not exist in the first place similar to the test found [here](https://github.com/supertokens/supertokens-node/blob/master/test/sessionExpress.test.js#L1128)
- test that ``refreshSession`` does not clear cookies if a session does not exist in the first place similar to the test found [here](https://github.com/supertokens/supertokens-node/blob/master/test/sessionExpress.test.js#L1167)
